name: Reward Contributor

on:
  pull_request:
    types: [closed]
    branches:
      - main
    # Only run when pull request is merged
    # (optional, as closing a pull request for other reasons will also trigger this)
    conditions:
      - github.event_name == 'pull_request'
      - github.event.action == 'closed'
      - github.event.pull_request.merged == true

jobs:
  reward_contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List modified files
        id: list_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files.txt
          echo "::set-output name=files::$(cat files.txt)"

      - name: Run Python script
        env:
          FILES: ${{ steps.list_files.outputs.files }}
        run: |
          python .github/scripts/reward_contributor.py $FILES
