name: Status Display

on: push

jobs:
  status-display:
    name: Status Display Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install requests python-dotenv

      - name: Creating invoice code (check logs)
        env:
          WALLET_BASE_URL: ${{secrets.WALLET_BASE_URL}}
          WALLET_API_KEY: ${{secrets.WALLET_API_KEY}}
          INVOICE_AMOUNT: 1
          CHECK_PAYMENT_ATTEMPTS: 3
          CHECK_PAYMENT_DELAY: 10
        working-directory: .github/scripts
        run: python create_invoice.py
