name: Status Display

on: push

jobs:
  status-display:
    name: Status Display Job
    runs-on: ubuntu-latest
    steps:
      - name: Run Status Display
        run: |
          echo "Preparing..."
          sleep 10
          echo "Working..."
          sleep 10
          echo "Done!"
