name: Status Display

on: push

jobs:
  status-display:
    name: Status Display Job
    runs-on: ubuntu-latest
    steps:
      - name: Creating payment code (check logs)
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("Creating payment code...");
            await new Promise(r => setTimeout(r, 10000));
            console.log("Your payment code: sdlfmslflsdf");
            console.log("You have 15 seconds to pay");
            await new Promise(r => setTimeout(r, 15000));
            console.log("Success!");
  
